# Generated by Django 5.1.4 on 2025-01-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hist_timestamp", models.DateTimeField(default="1980-01-01 00:00:00")),
                ("hist_timestamp_dst", models.CharField(default="s", max_length=1)),
                ("hcapi_subscript", models.IntegerField(default=0)),
                ("time", models.DateTimeField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("area", models.CharField(blank=True, max_length=8, null=True)),
                ("category", models.CharField(blank=True, max_length=10, null=True)),
                ("excdef", models.CharField(blank=True, max_length=8, null=True)),
                ("location", models.CharField(blank=True, max_length=12, null=True)),
                ("time_soe", models.DateTimeField(blank=True, null=True)),
                ("compid", models.CharField(blank=True, max_length=56, null=True)),
                ("seqnum", models.BigIntegerField(blank=True, null=True)),
                ("audible", models.IntegerField(blank=True, null=True)),
                ("event", models.IntegerField(blank=True, null=True)),
                ("abnormal", models.IntegerField(blank=True, null=True)),
                ("unackiss", models.IntegerField(blank=True, null=True)),
                ("priornum", models.BigIntegerField(blank=True, null=True)),
                ("ms", models.BigIntegerField(blank=True, null=True)),
                ("time_dst", models.CharField(blank=True, max_length=1, null=True)),
                ("time_soe_dst", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "alarm",
                "managed": True,
            },
        ),
    ]
